apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  username: YWRtaW4=
  password: YWRtaW4=
  db_host: MTAuMTI4LjE1LjIyMQ==
  db_name: cG9ydGZvbGlv
# echo -n 'data' | base64
# the secrets here are not in use
