steps:
  # Build container
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "${_LOCATION}-docker.pkg.dev/$_PROJECT_ID/${_AR_REPO}/${_IMAGE}",
        ".",
      ]
    # Push container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/george-test-335313/gcpdevops"]
timeout: 660s
